apiVersion: v1
items:
  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ef20-storage
    provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
    allowVolumeExpansion: true
    mountOptions:
      - dir_mode=0777
      - file_mode=0777
      - uid=0
      - gid=0
      - mfsymlinks
      - cache=strict
      - actimeo=30
    parameters:
      skuName: Standard_LRS
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: dstoken-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Mi
      storageClassName: ef20-storage

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: agconfig-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Mi
      storageClassName: ef20-storage      

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ef20-logs
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: ef20-storage  
 
kind: List
metadata: {}

